# Generated by Django 3.2.9 on 2021-11-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('status', models.BooleanField(verbose_name='status')),
                ('creation_date', models.DateField(verbose_name='Fecha alta')),
            ],
        ),
    ]
